### Get breeds

GET https://dogapi.dog/api/v2/breeds HTTP/1.1

### Get facts

GET https://dogapi.dog/api/v2/facts?limit=20 HTTP/1.1
content-type: application/json

### Get groups

GET https://dogapi.dog/api/v2/groups HTTP/1.1

###

GET https://dog.ceo/api/breeds/image/random HTTP/1.1
